#!/bin/bash
#set -x
 
LOCAL_REPO="git@github.com:Seagate/cortx-motr.git"
REMOTE_REPO=`git remote -v | grep "cortx-motr.git" | head -1 | cut -f 2 | cut -f 1 -d " "`

echo "repo local:$LOCAL_REPO | remote:$REMOTE_REPO"
if [[ $REMOTE_REPO != $LOCAL_REPO ]]; then
   echo bad repo $LOCAL_REPO $REMOTE_REPO
fi
echo "Error: Bad repo, should not push the changes to the remote repo"
exit 1

